### ISSUE TITLE
Exc_bad_access on dateFormat

### ISSUE THREAD

**Issue by cbigas-cgi** [BeauNouvelle/DateTextField#3]
Hello, 
i have an issue when i choose **dateFormat**
```
weak var birthdayTextField: DateTextField!

override func viewDidLoad() {
        super.viewDidLoad()
        // init
        self.birthdayTextField.becomeFirstResponder()
        self.birthdayTextField.dateFormat = .monthDayYear // Exc_bad_access issue here
        self.birthdayTextField.separator = "/"        
}
```

Help please.
(otherwise, good job. Very useful)

**Comment by BeauNouvelle** [comment]
Thanks for brining this up, I'll check it out for you.

**Comment by BeauNouvelle** [comment]
Ah, should have seen this before.
You're getting a bad access error because your `birthdayTextField` hasn't been initialised.
