### ISSUE TITLE
DateTextField won't work on device (TestFlight)

### ISSUE THREAD

**Issue by afMicWeg** [BeauNouvelle/DateTextField#4]
while working in simulator and on device when deployed via Xcode, DateTextField stopped working when installed e.g via TestFlight. Very strange behavior, have no idea what's going on.

Anybody can help?

Thx

Michael

**Comment by BeauNouvelle** [comment]
In what way is it broken?

**Comment by afMicWeg** [comment]
Sorry mate, problem was on my side. Seems that inheritation of delegates (UITextFieldDelegate) was messed up on my side. Gonna close this issue, thx for asking!

Kind regards.
